postgresql:
  restart: always
  image: armhf/postgres:9.6-2
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
gitlab:
  restart: always
  image: https://hub.docker.com/r/cfriedt/armhf-gitlab-ce/
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=false
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
redis:
  restart: always
  image: armhf/redis:latest
  command:
    - --loglevel warning
