postgresql:
  restart: always
  image: arm32v7/postgres:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
gitlab:
  restart: always
  image: cfriedt/armhf-gitlab-ce:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=false
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
redis:
  restart: always
  image: arm32/v7:latest
  command:
    - --loglevel warning
